Disable incorrect SSU enforcement in Brili reference interpreter
This line is incorrect. In particular, consider the following program as
a counterexample:
```
@main() {
  one: int = const 1;
  set shadow one;
  main.cond: bool = const true;
  set cond main.cond;
.test:
  cond: bool = get;
  shadow: int = get;
  br cond .false .end;
.false:
  false.cond: bool = const false;
  set cond false.cond;
  jmp .test;
.end:
  print shadow;
}
```
I claim the following about the above program.
1) It is in SSA.
2) It follows the explicitly documented static and dynamic restrictions
   on `set`/`get`.
3) It always terminates with the output `1`.

However, when I run `brili`, I obtain the following output:
```
-> bril2json < repro.bril | brili
error: get without corresponding set for shadow
```

I suspect that SSU is best enforced via a static check rather than a
dynamic runtime check.

This commit disables the overly conservative enforcement mechanism (and
removes the associated test). It also adds a regression test with the
above counterexample program.